service: ${file(./../../constants.yml):NAME}-resources-service

# endpoints
functions:
  resourcesCreate:
    handler: handler.resourcesCreate
    events:
      - http:
          path: resources
          method: post
          cors: true
      - schedule:
          name: ${file(./../../constants.yml):NAME}-resourcesCreate-${opt:stage, 'dev'}
          rate: ${file(./../../constants.yml):AWS_WARMUP_RATE}
          enabled: ${file(./../../constants.yml):AWS_WARMUP}
          input:
            warmup: true
  resourcesGet:
    handler: handler.resourcesGet
    events:
      - http:
          path: resources/{id}
          method: get
          cors: true
      - schedule:
          name: ${file(./../../constants.yml):NAME}-resourcesGet-${opt:stage, 'dev'}
          rate: ${file(./../../constants.yml):AWS_WARMUP_RATE}
          enabled: ${file(./../../constants.yml):AWS_WARMUP}
          input:
            warmup: true
  resourcesList:
    handler: handler.resourcesList
    events:
      - http:
          path: resources
          method: get
          cors: true
      - schedule:
          name: ${file(./../../constants.yml):NAME}-resourcesList-${opt:stage, 'dev'}
          rate: ${file(./../../constants.yml):AWS_WARMUP_RATE}
          enabled: ${file(./../../constants.yml):AWS_WARMUP}
          input:
            warmup: true
  resourcesUpdate:
    handler: handler.resourcesUpdate
    events:
      - http:
          path: resources/{id}
          method: put
          cors: true
      - schedule:
          name: ${file(./../../constants.yml):NAME}-resourcesUpdate-${opt:stage, 'dev'}
          rate: ${file(./../../constants.yml):AWS_WARMUP_RATE}
          enabled: ${file(./../../constants.yml):AWS_WARMUP}
          input:
            warmup: true
  resourcesDelete:
    handler: handler.resourcesDelete
    events:
      - http:
          path: resources/{id}
          method: delete
          cors: true
      - schedule:
          name: ${file(./../../constants.yml):NAME}-resourcesDelete-${opt:stage, 'dev'}
          rate: ${file(./../../constants.yml):AWS_WARMUP_RATE}
          enabled: ${file(./../../constants.yml):AWS_WARMUP}
          input:
            warmup: true

# config
provider:
  name: aws
  runtime: ${file(./../../constants.yml):NODE_VERSION}
  stage: ${opt:stage, 'dev'}
  role: ${file(./../../serverless.env.yml):AWS_ROLE}
  memorySize: ${file(./../../constants.yml):AWS_MEMORY}
  timeout: ${file(./../../constants.yml):AWS_TIMEOUT}
  vpc:
    securityGroupIds:
      - ${file(./../../serverless.env.yml):VPC_SECURITY}
    subnetIds:
      - ${file(./../../serverless.env.yml):VPC_SUBNET1}
      - ${file(./../../serverless.env.yml):VPC_SUBNET2}
      - ${file(./../../serverless.env.yml):VPC_SUBNET3}
      - ${file(./../../serverless.env.yml):VPC_SUBNET4}
  apiGateway:
    restApiId: ${file(./../../serverless.env.yml):AWS_API_ID_${self:custom.environments.${self:provider.stage}}}
    restApiRootResourceId: ${file(./../../serverless.env.yml):AWS_API_ROOT_ID_${self:custom.environments.${self:provider.stage}}}
  environment:
    STAGE: ${self:provider.stage}
    DB_HOST: ${file(./../../serverless.env.yml):DB_HOST}
    DB_USER: ${file(./../../serverless.env.yml):DB_USER}
    DB_PASS: ${file(./../../serverless.env.yml):DB_PASS}
    DB_NAME: ${file(./../../serverless.env.yml):DB_NAME}

plugins:
  - serverless-webpack

custom:
  environments:
    dev: DEV
    prod: PROD
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
